spring.application.name=BugBountyPlatform

spring.datasource.url=jdbc:mysql://localhost:3306/dsw1_bounty?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false